### ISSUE TITLE
Cannot run init as root

### ISSUE THREAD

**Issue by perdiesman** [zombodb/pgx#163]
Since the latest version runs initdb I can no longer run the cargo pgx init command as root.  I am trying to compile ZomboDB from source.  I can run the init command as postgres but that user doesn't have permission to install the extension then so that has to be run as root but needs the pgx init run first.

**Comment by eeeebbbbrrrr** [comment]
My suggestion here is to do everything as non-root, then copy the resulting artifacts in place using sudo.

Alternatively, use ZDB's "docker-build-system", either with one of existing docker images, or make your own for your environment, modeled after an existing one.

I don't see us making a change to `cargo pgx` here -- it really does need to initdb early like it does now.

**Comment by Hoverbear** [comment]
Since you didn't include the errors you faced, I can't really offer good suggestions.

Generally you shouldn't be building software as `root`, I suggest you use a user which can install the extension to build it.

Otherwise, you can maybe set `CARGO_PGX_HOME` and possibly trick it? Similar to how we do with https://github.com/zombodb/pgx/blob/0ff01959c7b9130b10965c9bf22cba95f100c520/nix/templates/default/default.nix#L56.

**Comment by perdiesman** [comment]
Just an FYI for anyone else with this issue, the exporting of PGX_HOME that @Hoverbear suggested worked perfect for me.  I was able to do an init as postgres then ran the install as root after setting: `export PGX_HOME=~postgres/.pgx`

Thanks for the help
