### ISSUE TITLE
Can this be used for FDW?

### ISSUE THREAD

**Issue by bbigras** [zombodb/pgx#7]

**Comment by eeeebbbbrrrr** [comment]
You absolutely could implement a FDW with this. 

I think we’ll need to get those Postgres headers included in the pgx-pg-sys crate, tho.

I’ll take a look at doing that this week.

**Comment by eeeebbbbrrrr** [comment]
Okay, this will be released as part of v0.0.7 -- which is coming in an hour or so!

**Comment by eeeebbbbrrrr** [comment]
released to crates.io

**Comment by bbigras** [comment]
Awesome :heart: 

Any example that could be used with `CREATE EXTENSION <something>;` ... `CREATE SERVER <something> FOREIGN DATA WRAPPER <something>`?

**Comment by eeeebbbbrrrr** [comment]
Oh goodness.  Not yet!  ;)

Right now, that's left as an exercise for the programmer.  The FDW api is fairly complex, and ultimately I'd want a safe Rust wrapper around it.

The API is only exposed as a low-level, unsafe Rust interface in the `pgx::pg_sys` module.  You'd have to [start here](https://www.postgresql.org/docs/12/fdwhandler.html) and work your way through implementing everything.

I have written a few FDW's (in C) in years past, so I can provide some bit of guidance if you go down this road.  And I'd most definitely accept a PR that exposes a safe FDW interface.

**Comment by bbigras** [comment]
Gotcha. Thanks! :+1:

**Comment by bjmc** [comment]
Hi, sorry to bump a closed thread, but I'm looking into implementing a foreign data wrapper (ideally using `pgrx`, though I'm also considering [alternatives](https://github.com/turbot/steampipe-postgres-fdw/tree/develop/fdw)).

Has there been any movement on this topic since 2020? Any examples I could follow?

I'm thinking if I wind up writing a bunch of Rust wrappers and glue code myself, I might as well try to do it in a generic way that could be merged upstream. @eeeebbbbrrrr if you're interested, I'd very much appreciate any guidance you can offer.

From reading [the docs](https://www.postgresql.org/docs/12/fdwhandler.html) it seems like the bulk of the effort will be the callback functions. I was wondering if maybe `cargo pgrx new` could be extended to generate a skeleton template for a FDW with all the functions and their signatures stubbed out and ready to be implemented.

Is it worth opening another thread for discussion? Or wait until I'm further along and submit a PR then?

**Comment by eeeebbbbrrrr** [comment]
hi @bjmc, check out https://github.com/supabase/wrappers.  They've done some really solid work using pgrx to made a nice abstraction over the FDW api.  And it includes wrappers for quite a few disparate data sources.

Even as a core pgrx developer, if I were to implement a FDW today, that's where I'd start.

**Comment by bjmc** [comment]
Thank you! This looks extremely helpful.
